### ISSUE TITLE
Zed doesn't trigger wakatime heartbeats but Helix does

### ISSUE THREAD

**Issue by zoedsoupe** [wakatime/zed-wakatime#16]
I'm having some trouble to use wakatime with Zed, although it works perfectly with Helix.

I'm on MacOS Sequoia 15.3 (m1) and both `wakatime-lsp v0.1.1` and `wakatime-cli v1.102.3` are on $PATH, the first one installed manually and the latter managed by `nix`.

Zed logs doesn't shows nothing, even errors for this extension, so there's a way that i can debug the wakatime Zed extension? my `.wakatime.cfg` looks like something:

```toml
[settings]
api_key=...
include_only_with_project_file=true
exclude_unknown_project=true
```

and all my tracked projects have a `.wakatime-project` file filled. opening the same project on helix with custom lsp (aka `wakatime-lsp`) works perfectly.
